### PR TITLE
Fixed an issue with pre mode needs to be re-enterable after exiting

### LINKED ISSUE #712: pre mode needs to be re-enterable after exiting
## Affected Packages

pkg:@changesets/pre

## Problem

Below is the scene that how I used and the problem

```bash
# do something, and want to bump a prerelease alpha version to test

$ changeset pre enter alpha
🦋  success Entered pre mode with tag alpha
🦋  info Run `changeset version` to version packages with prerelease versions

# do something, like commit and version

$ changeset pre exit
🦋  success Exited pre mode
🦋  info Run `changeset version` to version packages with normal versions

# do something ...
# I don't want to bump a patch version or publish now,
# and want to continue bump alpha version,
#
# so I need enter pre mode again,
# in this time, it throw an Error, even though I have really exited pre mode above
$ changeset pre enter alpha
🦋  error `changeset pre enter` cannot be run when in pre mode
🦋  info If you're trying to exit pre mode, run `changeset pre exit`

$ cat .changeset/pre.json
{
  "mode": "exit",
  "tag": "alpha",
  "initialVersions": {
    ...
  },
  "changesets": [
    "xxx"
  ]
}
```

I know I can edit `pre.json` manually, but I think it needs to be improved in changesets.

## Proposed solution

[Here](https://github.com/changesets/changesets/blob/%40changesets/pre%401.0.8/packages/pre/src/index.ts#L52-L54) the code of function [`enterPre`](https://github.com/changesets/changesets/blob/%40changesets/pre%401.0.8/packages/pre/src/index.ts#L52-L54), and I noticed there is a TODO that say `verify that the pre state isn't broken`, I think it means like this:

```typescript
  export async function enterPre(cwd: string, tag: string) {
   let packages = await getPackages(cwd);
   let preStatePath = path.resolve(packages.root.dir, ".changeset", "pre.json");
-  // TODO: verify that the pre state isn't broken
   let preState: PreState | undefined = await readPreState(packages.root.dir);
-  if (preState !== undefined) {
+  if (preState !== undefined && preState.mode === "pre") {
     throw new PreEnterButInPreModeError();
   }
   let newPreState: PreState = {
     mode: "pre",
     tag,
     initialVersions: {},
-    changesets: []
+    changesets: preState?.changesets ?? []
   };
   for (let pkg of packages.packages) {
     newPreState.initialVersions[pkg.packageJson.name] = pkg.packageJson.version;
   }
   await fs.writeFile(preStatePath, JSON.stringify(newPreState, null, 2) + "\n");
 }
```

### PR DESCRIPTION
**Pull request by zthxxx**
closes #712

### CODE REVIEW

File: packages/pre/src/index.ts [hunk 1]
```diff
@@ -47,16 +47,16 @@ export async function exitPre(cwd: string) {
 export async function enterPre(cwd: string, tag: string) {
   let packages = await getPackages(cwd);
   let preStatePath = path.resolve(packages.root.dir, ".changeset", "pre.json");
-  // TODO: verify that the pre state isn't broken
-  let preState = await readPreState(packages.root.dir);
-  if (preState !== undefined) {
+  let preState: PreState | undefined = await readPreState(packages.root.dir);
+  // can't reenter if pre mode still exists, but enterable if already exited
+  if (preState?.mode === "pre") {
```
Comment (Andarist) [inline packages/pre/src/index.ts:52]: IMHO this makes sense

File: packages/pre/src/index.ts [hunk 2]
```diff
@@ -47,16 +47,16 @@ export async function exitPre(cwd: string) {
...
     throw new PreEnterButInPreModeError();
   }
   let newPreState: PreState = {
     mode: "pre",
     tag,
     initialVersions: {},
```
Comment (Andarist) [inline packages/pre/src/index.ts:58]: should `initialVersions` be "reset" though? My first instinct would be that the `newPreState` should just have `tag` and `mode` updated

File: packages/pre/src/index.test.ts [hunk 3]
```diff
@@ -39,6 +49,21 @@ describe("enterPre", () => {
       PreEnterButInPreModeError
     );
   });
+  it("should enter if already exited pre mode", async () => {
```
Comment (Andarist) [inline packages/pre/src/index.test.ts:52]: could you also add a test at the CLI level too? it would go [here](https://github.com/changesets/changesets/blob/ab8f2b29d5cf921d97987a665051b67a7ec55ed3/packages/cli/src/commands/pre/index.test.ts#L27) and I imagine it would look smth like this:
1. `f.copy`
2. `changeset pre enter beta`
3. do stuff
4. `changeset pre exit`
5. `changeset pre enter beta`

File: packages/pre/src/index.ts (hunk 2 above)
Comment (Andarist) [reply packages/pre/src/index.ts:58]: ah, this is only initializing the value, and versions are filled in in the loop below this. So the question is - should the current versions be put as `initialVersions`? or should the existing `initialVersions` be preserved?

Comment (zthxxx) [reply packages/pre/src/index.ts:58]: It doesn't make any difference, the `initialVersions` not really be used anywhere yet.

File: packages/pre/src/index.test.ts (hunk 3 above)
Comment (zthxxx) [reply packages/pre/src/index.test.ts:52]: Done.

Due to both `exit` `enter` are independent operator, and the connection between them is only `pre.json`,

so I only test the "re-enter" step, rather than the flow 2 to 4 in your given

File: packages/pre/src/index.ts (hunk 2 above)
Comment (Andarist) [reply packages/pre/src/index.ts:58]: You are right, `initialVersions` are not actually used anywhere - I'm not sure why do we even keep this info around 🤔 I've asked Mitchell a question about this.

File: packages/pre/src/index.ts (hunk 1 above)
Comment (zthxxx) [reply packages/pre/src/index.ts:52]: I'm not sure what need I do or not?  👀

Remove the `// comment`, or remove types, or just click resolve this conversation?

Comment (Andarist) [reply packages/pre/src/index.ts:52]: i was just confirming that this makes sense to me 😉 nothing to change here :)

File: packages/pre/src/index.ts (hunk 2 above)
Comment (zthxxx) [reply packages/pre/src/index.ts:58]: Any update about this question?

Or It's exactly another issue and not about this PR "re-enterable pre mod", so can I just click "resolve conversation" then open an issue to discuss?

File: packages/pre/src/index.ts [hunk 4]
```diff
@@ -47,16 +47,16 @@ export async function exitPre(cwd: string) {
 export async function enterPre(cwd: string, tag: string) {
   let packages = await getPackages(cwd);
   let preStatePath = path.resolve(packages.root.dir, ".changeset", "pre.json");
-  // TODO: verify that the pre state isn't broken
-  let preState = await readPreState(packages.root.dir);
-  if (preState !== undefined) {
+  let preState: PreState | undefined = await readPreState(packages.root.dir);
+  // can't reenter if pre mode still exists, but enterable if already exited
```
Comment (Andarist) [inline packages/pre/src/index.ts:51]:
```suggestion
  // can't reenter if pre mode still exists, but we should allow exited pre mode to be reentered
```

File: .changeset/thirty-panthers-film.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@changesets/pre": patch
+---
+
+pre mode needs to be re-enterable after exiting, close #712
```
Comment (Andarist) [inline .changeset/thirty-panthers-film.md:5]:
```suggestion
---
---
```

File: .changeset/afraid-dots-know.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+"@changesets/cli": patch
+---
```
Comment (Andarist) [inline .changeset/afraid-dots-know.md:3]:
```suggestion
---
"@changesets/cli": patch
"@changesets/pre": patch
---
```

File: .changeset/afraid-dots-know.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
...
+
+support re-enter pre mode if already exited
```
Comment (Andarist) [inline .changeset/afraid-dots-know.md:5]:
```suggestion
Fixed an issue with not being to reenter exited pre mode.
```

File: .changeset/afraid-dots-know.md [hunk 8]
```diff
@@ -0,0 +1,6 @@
+---
+"@changesets/cli": patch
+"@changesets/pre": patch
+---
+
+Fixed an issue with not being to reenter exited pre mode.
```
Comment (Andarist) [inline .changeset/afraid-dots-know.md:6]:
```suggestion
Fixed an issue with not being able to reenter exited pre mode.
```
