### PR TITLE
Fix return value of `getCurrentCommitId`

### LINKED ISSUE #888: Commit hash with quotation marks results in invalid snapshot version
## Affected Packages

@changesets/git, @changesets/cli, @changesets/assemble-release-plan

## Problem

Function `getCurrentCommitId` from package `@changesets/git` returns commit hash with quotation marks. This value is then [used](https://github.com/changesets/changesets/blob/e4204820cdb93d22a3c7a27f452a0ab30db6369a/packages/cli/src/commands/version/index.ts#L78) when generating snapshot version: with config option `prereleaseTemplate` set to `'${tag}.{commit}'` it results to e.g.: `'2.1.0-foobar."41b793f"'` (instead of `'2.1.0-foobar.41b793f'`) and because such semver is invalid, error is thrown.

## Proposed solution

`getCurrentCommitId` should return commit hash with quotation marks removed, but I'm not sure if any other package depends upon quotation marks actually being present. Anyway, the quick solution is in #889.

### PR DESCRIPTION
**Pull request by jakubmazanec**
fixes #888

### CODE REVIEW

File: packages/git/src/index.ts [hunk 1]
```diff
@@ -296,5 +296,6 @@ export async function getCurrentCommitId({
     await spawn("git", ["show", `--format="%h"`, "--no-patch"], { cwd })
   ).stdout
     .toString()
-    .trim();
+    .trim()
+    .replace(/"/g, "");
```
Comment (Andarist) [inline packages/git/src/index.ts:300]: Interesting, `git show --format="%h" --no-patch` doesnt add quotation marks in the stdout for me. What system and git version are you using?

File: packages/git/src/index.ts [hunk 2]
```diff
@@ -296,5 +296,6 @@ export async function getCurrentCommitId({
     await spawn("git", ["show", `--format="%h"`, "--no-patch"], { cwd })
```
Comment (Andarist) [inline packages/git/src/index.ts:296]: I wonder if the reason we end up with those quotation marks isn't that we include them here in the `format`. I've checked on my machine and this works fine too:
```suggestion
    await spawn("git", ["show", "--format=%h", "--no-patch"], { cwd })
```

Alternatively we could also just switch to using this:
```suggestion
    await spawn("git", ["rev-parse", "--short", "HEAD"], { cwd })
```
It seems to be better suited for this job anyway.

File: packages/git/src/index.ts (hunk 1 above)
Comment (jakubmazanec) [reply packages/git/src/index.ts:300]: Windows 10 Enterprise 21H1, git 2.30.1.windows.1.
When i run `git show --format="%h" --no-patch` in PowerShell, I also see only the hash 🤔

File: packages/git/src/index.ts (hunk 2 above)
Comment (jakubmazanec) [reply packages/git/src/index.ts]: Both suggestion seem to solve the problem. I agree that the second one seems to be better for this. I updated the PR.

File: .changeset/kind-beds-divide.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@changesets/git": patch
+---
+
+Fixes `getCurrentCommitId` so that the returned value doesn't contain quotation marks.
```
Comment (Andarist) [inline .changeset/kind-beds-divide.md:5]:
```suggestion
Fixes `getCurrentCommitId` so that the returned value doesn't contain quotation marks on some Windows machines.
```

**Review by Andarist — APPROVED** [review]
